### ISSUE TITLE
Создание отчета

### ISSUE THREAD

**Issue by an-egorova** [an-egorova/kmeans_algoritm#13]
Необходимо написать шаблон отчета РГР по математике
Шаблон должен включать в себя:

- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #19

**Comment by an-egorova** [comment]
Титульник + описание логики алгоритма + схема документа

[rgr_math_1_semestr.docx](https://github.com/an-egorova/kmeans_algoritm/files/7671526/rgr_math_1_semestr.docx)

**Comment by an-egorova** [comment]
[rgr_math_1_semestr.docx](https://github.com/an-egorova/kmeans_algoritm/files/7676368/rgr_math_1_semestr.docx)

**Comment by Miguniya** [comment]
[rgr_math_1_semestr.docx](https://github.com/an-egorova/kmeans_algoritm/files/7697065/rgr_math_1_semestr.docx)
Заполнила генерацию точек и описание сохранения в файл

**Comment by an-egorova** [comment]
[rgr_math_1_semestr.docx](https://github.com/an-egorova/kmeans_algoritm/files/7705845/rgr_math_1_semestr.docx)
описала кластеризацию
